### ISSUE TITLE
Info: Alternative way to solve this issue

### ISSUE THREAD

**Issue by 1ras** [cosote/R216-Z#4]
This is not a bug report but an alternative way to solve this issue. The R216-Z supports reconnections out of the box for networks listed in the autoconnect database. The issue is that not all networks are listed there. But they can be manually added with this steps:

1. Connect the router with a USB cable to the PC. Make sure a network adapter appears.

2. Set up Wifi connection to the router and connect to it.

3. Connect to the web interface of the router and login (default password is admin):
`http://192.168.0.1/
`
4. Switch router to ADB mode by accessing
`http://192.168.0.1/goform/goform_set_cmd_process?goformId=USB_MODE_SWITCH&usb_mode=6`

5. Install the Android Debug Bridge (command for Debian Linux):
`apt install adb`

6. List the Android devices and the router should be shown as a device:
`adb devices`

7. Download auto_apn.db from the R216-Z
`adb pull /usr/zte_web/web/auto_apn/auto_apn.db`

8. Take a backup and upload the backup (optional)
```
cp auto_apn.db auto_apn.db.orig
adb push auto_apn.db.orig /usr/zte_web/web/auto_apn/
```

9. Add e.g. the missing German network providers to the auto_apn.db
```
sqlite3 auto_apn.db
INSERT INTO apn_list VALUES (26201, "Telekom Deutschland", "", "", "*99#", 0, "internet.telekom", 1, "", "", 1, "", "IPv4v6", "PAP", 0, 0, "Telekom Deutschland", "Contract", "Yes", 60, "Telekom Deutschland", "www.telekom.de", 0, "", "Yes", "Yes");
INSERT INTO apn_list VALUES (26203, "Telefonica", "", "", "*99#", 0, "internet", 1, "", "", 1, "", "IPv4v6", "PAP", 0, 0, "Telefonica Contract", "Contract", "Yes", 60, "Telefonica", "www.telefonica.de", 0, "", "Yes", "Yes");
INSERT INTO apn_list VALUES (26203, "Telefonica", "", "", "*99#", 0, "pinternet.interkom.de", 1, "", "", 1, "", "IPv4v6", "PAP", 0, 0, "Telefonica Prepaid", "Prepaid", "Yes", 60, "Telefonica", "www.telefonica.de", 1, "", "Yes", "Yes");
INSERT INTO apn_list VALUES (26207, "o2", "", "", "*99#", 0, "internet", 1, "", "", 1, "", "IPv4v6", "PAP", 0, 0, "o2 Contract", "Contract", "Yes", 60, "o2", "www.o2online.de", 0, "", "Yes", "Yes");
INSERT INTO apn_list VALUES (26207, "o2", "", "", "*99#", 0, "pinternet.interkom.de", 1, "", "", 1, "", "IPv4v6", "PAP", 0, 0, "o2 Prepaid", "Prepaid", "Yes", 60, "o2", "www.o2online.de", 1, "", "Yes", "Yes");
.quit
```

10. Upload modified auto_apn.db to the R216-Z
`adb push auto_apn.db /usr/zte_web/web/auto_apn/`

11. Reboot the router with
`adb shell reboot`
or through the web interface: Settings > Device > Reboot

This works with firmware version 4.1 as available at https://www.vodafone.nl/support/telecombeheer/software-en-downloads

Reference (Russian): https://4pda.ru/forum/index.php?showtopic=686258&st=60

**Comment by madera17** [comment]
Thank you for this. I am using the device on O2 UK and was experiencing the same lack of connection after reboot.

After adding the O2 UK APN details to the sqlite3 file auto_apn.db it connect immediately after reboot.

**Comment by 1ras** [comment]
Thanks for the feedback.

In case someone is looking for the mobile country codes (MCC) and mobile network codes (MNC) of a network he like to add (the MCC/MNC tuple is used at the first column of the table),  here is a nice list: https://en.wikipedia.org/wiki/Mobile_country_code

**Comment by madera17** [comment]
Danke Andreas.

Your item helped me very much.

**Comment by cosote** [comment]
Great job! I've added the apn_list update to the tool.
